const productsType = {
  PRODUCTS_REQUEST_FETCH: 'PRODUCTS_REQUEST_FETCH',
  PRODUCTS_REQUEST_SUCCESS: 'PRODUCTS_REQUEST_SUCCESS',
  PRODUCTS_REQUEST_ERROR: 'PRODUCTS_REQUEST_ERROR',

  PRODUCTS_CHANGE: 'PRODUCTS_CHANGE',
};

export default productsType;
