const productType = {
  PRODUCT_REQUEST_FEATCH: 'PRODUCT_REQUEST_FEATCH',
  PRODUCT_REQUEST_SUCCESS: 'PRODUCT_REQUEST_SUCCESS',
  PRODUCT_REQUEST_ERROR: 'PRODUCT_REQUEST_ERROR',
};

export default productType;
